### ISSUE TITLE
Incorrect date in flight listings

### ISSUE THREAD

**Issue by romanmic** [skylines-project/skylines#659] opened 2017-05-19 17:28 UTC
When flight listings are viewed from browsers in time zones west of UTC  0 shown flight dates are off by one day.

**Comment by Turbo87** [comment] 2017-05-19 17:35
@romanmic interesting, thanks for reporting that

**Comment by romanmic** [comment] 2017-05-19 17:41
I brought thus issue last September on Skylines forum to no avail.
https://forum.xcsoar.org/viewtopic.php?f=20&t=2767
Wrong board, I guess :)

It's easy to reproduce: on my Mac I just change the time zone from -4 to +1
and all is fine.
Both Chrome and Safari exhibit the same behavior,


Thanks for looking into this.

Best,
Roman

**Comment by romanmic** [comment] 2017-11-01 15:41
I understand there are priorities but this gets in a way of using Skylines effectively here in the Western hemisphere.
Thank you for your great work on XCSoar/Skylines ..
Roman

**Comment by Turbo87** [comment] 2017-11-06 08:40
@romanmic sorry, I forgot about this issue 🤦‍♂️ 

The issue is fixed by https://github.com/skylines-project/skylines/pull/702 and already deployed to the server. Please let me know if you still see that issue and thanks again for reporting it!

**Closed** 2017-11-06 09:53 UTC
Labels: bug

**Comment by romanmic** [comment] 2017-11-06 13:05
Hi Tobias,
Thank you for responding so quickly to my bump.
I can imagine a low priority item like that slips between the cracks when
you have to keep so many ball in the air :)

Life is much better now.
Fly safe,
Roman
