### ISSUE TITLE
Skyline Live simultaneous pilots show 24 hours appart

### ISSUE THREAD

**Issue by BrunoDijols** [skylines-project/skylines#365] opened 2015-01-11 11:32 UTC
Two pilots tracking at the same time and plot on the same map (with "," between our ids 1998 and 4210) are show on the map with 24 hours difference. Screen shot and explainations attached.
![simultaneous_tracking_shows24hours_appart](https://cloud.githubusercontent.com/assets/10484949/5695071/e58cc42a-998d-11e4-91db-e1406ef380c9.jpg)

**Comment by Philippe-P** [comment] 2015-01-11 13:14
Could it have something to do with the fact that your track started on the 10th and continued (in the eyes of Skylines at least) on the 11th, while the second one started before noon the 11th, that is within the 12h "memory" of the tracking map?

**Comment by BrunoDijols** [comment] 2015-01-12 20:14
So it might be related to this bug : https://github.com/skylines-project/skylines/issues/208

**Comment by Philippe-P** [comment] 2015-01-12 21:40
Ah ben là, on se sent moins seuls! C'est sûr que les pov mecs qui sont à 
UT +/-12 doivent regretter de ne pas habiter à Greenwich ;-)

**Comment by BrunoDijols** [comment] 2015-01-12 21:42
Ca leur apprendra.à ne pas faire comme tout le monde.

2015-01-12 22:40 GMT+01:00 Philippe-P <notifications@github.com>:

**Comment by Turbo87** [comment] 2016-10-27 17:57
I tend to agree that this is most likely a duplicate of #208

**Closed by Turbo87** 2016-10-27 17:57 UTC
